site_name: Unofficial Ryver API Docs
theme: readthedocs
pages:
- Home: "index.md"
- Guide:
  - "General notes": "guide/general.md"
  - "Making requests": "guide/requests.md"
- Entities:
  - "Entity.Forum": "entities/entity.forum.md"
  - "Entity.Workroom": "entities/entity.workroom.md"
- Chat:
  - "Chat.PostMessage": "chat/postmessage.md"
  - "Chat.History": "chat/history.md"
  - "Tabs.Chat.MarkAsRead": "chat/markasread.md"
